spring:
  application:
    name: registry

  datasource:
    url: jdbc:postgresql://localhost:5432/registry
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: WARN
    org.springframework: ERROR
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
    com.ralphmarondev.registry: INFO


server:
  address: 0.0.0.0
  port: 3333
  servlet:
    context-path: /api/
